{
 "title": "BMS",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Charge/Discharge Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, charging_enabled AS \"Charging Enabled\", discharging_enabled AS \"Discharging Enabled\", ischarging AS \"Charging\", isdischarging AS \"Discharging\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, soc AS \"State of Charge\" FROM jkbms.bms ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, soc AS \"State of Charge\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, voltage FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "description": "Postive = Discharging\nNegative = Charging",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, current AS \"Current\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, cell0_voltage AS \"Cell 1 Voltage\", cell1_voltage AS \"Cell 2 Voltage\", cell2_voltage AS \"Cell 3 Voltage\", cell3_voltage AS \"Cell 4 Voltage\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, battery_temp AS \"Battery Temperature\", power_temp AS \"BMS Temperature\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, cell0_voltage AS \"Cell 1 Voltage\", cell1_voltage AS \"Cell 2 Voltage\", cell2_voltage AS \"Cell 3 Voltage\", cell3_voltage AS \"Cell 4 Voltage\" FROM jkbms.bms ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Battery Cycles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, cycles AS \"Battery Cycles\" FROM jkbms.bms "
    }
   ]
  },
  {
   "title": "Cell Voltage Delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "jkbms",
     "rawSql": "SELECT date, cell_voltage_delta AS \"Cell Voltage Delta\" FROM jkbms.bms "
    }
   ]
  }
 ]
}